
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /images
  static_dir: static/img

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest




env_variables:
  DB_HOST: "nithin-268012:asia-south1:smarteruser"
  USER: "smarteruser"
  PASSWORD: "smarteruser"
  DATABASE: "clientdb9"


